#!/usr/bin/ruby
require 'rubygems'
require 'xmlsimple'
require 'pp'

# TheHat modules
require_relative 'wfengine'

workflow = Workflow.new(ARGV[0])
plan = XmlSimple.xml_in(ARGV[1])
tasks = Hash.new
plan['tasks'][0]['task'].each {
	|task|
	tasks[task['id']] = task
}

resources = Hash.new
plan['resources'][0]['resource'].each {
	|resource|
	resources[resource['id']] = resource
}


allocations = Hash.new
plan['allocations'][0]['allocation'].each {
	|allocation|
	allocations[allocation['task-id']] = allocation['resource-id']
}

tasks.each {
	|id,task|
	stepValues = Hash.new
	if task['note']
		task['note'].gsub('\n',"\n").split("\n").each {
			|note|
			key,value = note.split(':')
			stepValues[key] = value
		}
	end
	if stepValues['group']
		stepValues['group'] = stepValues['group'].split(',')
	end
	stepValues['name'] = "task#{id.to_s}"
	if allocations[id.to_s]
		stepValues['owner'] = resources[allocations[id.to_s]]['name']
	end
	if task['predecessors']
		gates = Array.new
		task['predecessors'][0]['predecessor'].each {
			|predecessor|
			gates.push("task#{predecessor['predecessor-id']}")
		}
		stepValues['gates'] = gates
	end
	# NOTE: api needs to change to simplify this
	workflow.steps[stepValues['name']]=Step.new(workflow,stepValues['name'],stepValues)
}
workflow.saveToFile(ARGV[2])

