#!/usr/bin/ruby
###########################################################################
# This file is part of TheHat - an interactive workflow system
# Copyright (C) 2007-2014 by David Parker. All rights reserved
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
###########################################################################

require_relative 'wfappframe'

class TTYFrontend < HatApp
	def run
		print @workflow.messages
		@workflow.clearMessages
		stdin = IO.new(1,'r')
		done = false
		line=''
		while not done
			print"\nworkflow(#{@workflow.name.to_s})> "
			line = stdin.gets.chomp
			if line
				case line
					when 'quit'
						done = true
					else
						@workflow.processCommand(ENV['USER'],line)
						print @workflow.messages
						@workflow.clearMessages
				end
			end
		end
	end
end

TTYFrontend.new.run
